# Project 3 -- Jazmin Pulido

**TA Help:** N/A

- Helped with...
    
**Collaboration:** N/A
    
- Helped with...

## Question 1

Using the 1990 airport data, find the average arrival delay for flights arriving to each airport.

In [1]:
import pandas as pd
myDF = pd.read_csv("/anvil/projects/tdm/data/flights/subset/1990.csv")
pd.set_option('display.max_rows', None)
myDF.groupby('Dest')['ArrDelay'].mean()

Dest
ABE     4.774940
ABQ     7.772013
ACY     5.588076
AGS     8.358385
ALB     7.511260
AMA     8.567987
ANC    11.361536
ATL     8.597035
ATW   -11.253012
AUS     6.218884
AVL     5.561917
AVP     7.239102
AZO     3.334252
BDL     7.501587
BET    11.801754
BFL     5.705599
BGM     4.609019
BGR    11.619406
BHM     5.618216
BIL     4.306908
BIS     4.325692
BLI     6.571663
BNA     2.990541
BOI     7.802144
BOS     8.681390
BTM     6.111433
BTR     7.727585
BTV     7.184737
BUF     7.623859
BUR     2.977912
BWI     6.117801
BZN     6.008305
CAE     8.454399
CAK     5.693481
CCR     1.058360
CDV     8.376488
CHA     4.973240
CHO     1.202899
CHS     6.199248
CID     7.011452
CLE     6.613217
CLT     4.672193
CMH     6.809549
CMI     4.130476
COS     6.412706
CPR     2.165428
CRP     8.065865
CRW     4.073368
CSG     9.576809
CVG     6.963399
DAB     8.970992
DAL     6.657802
DAY     4.349131
DCA     4.995616
DEN     8.176495
DET     7.003241
DFW     7.895275
DLH     2.092912
DRO     8.512270
DSM     7.854620
DTW     4.494812
EFD     1.714906
EGE    19.767606
ELM     5.068319
ELP     7.591237
ERI    10.334065
EUG     7.310419
EVV     1.030660
EWR    10.903922
EYW     2.352344
FAI    13.715238
FAR     6.487277
FAT     6.104785
FAY     4.626731
FCA     9.362340
FLG     4.606115
FLL     7.299241
FNT     7.088152
FSD     5.740753
FWA     5.075323
GCN     5.231303
GEG     7.734324
GFK     5.158886
GJT     6.406498
GNV     6.881706
GPT    -2.193137
GRB     2.871899
GRR     6.038218
GSO     5.930502
GSP     5.207854
GST     5.843373
GTF     4.536173
GUC    12.874194
GUM     6.956490
HDN    12.991055
HLN     5.775599
HNL     8.482858
HOU     7.463272
HPN     7.098569
HRL     6.350517
HSV     5.297237
HTS     0.164094
IAD     3.775034
IAH     7.521459
ICT     5.335067
IDA     5.316095
ILM     2.909057
IND     6.110519
ISO     2.047059
ISP     5.632582
ITH     5.904255
JAC     6.813785
JAN     6.772257
JAX     8.032874
JFK     8.567413
JNU    10.103102
KOA     5.623547
KTN    11.180851
LAN     1.454231
LAS     6.340679
LAX     6.779259
LBB     7.384796
LEX     8.916368
LFT     1.282288
LGA     9.741541
LGB     6.552703
LIH     6.982906
LIT     9.241714
LNK     8.099789
LSE     2.272727
LYH     1.934211
MAF     6.150701
MBS     5.262454
MCI     6.683866
MCO     7.436247
MDT     6.134694
MDW     6.148504
MEM     1.680644
MFE     6.357101
MFR     5.997268
MGM     8.027061
MHT     7.717308
MIA     4.637924
MKC          NaN
MKE     5.675064
MLB     7.236101
MLI     6.687482
MLU    11.687854
MOB     6.812799
MOT     0.822211
MRY     4.212573
MSN     5.260940
MSO     5.265374
MSP     4.161600
MSY     6.962229
MYR     2.934494
OAJ     3.487007
OAK     4.159836
OGG     5.294616
OKC     8.151771
OMA     6.698528
OME     9.191268
ONT     6.904306
ORD     7.279122
ORF     5.774474
ORH     5.244295
OTZ    10.460819
PBI     7.941035
PDX     6.506988
PHF     4.002979
PHL     9.451961
PHX     6.952283
PIA     5.703983
PIT     6.397241
PMD    -1.022398
PNS     5.301025
PSC     8.784916
PSE    30.533333
PSG    10.740496
PSP     5.731365
PUB     1.265643
PVD     6.601589
PWM     9.114453
RAP     4.070611
RDM    23.883929
RDU     2.724541
RIC     5.670268
RNO     7.144272
ROA     4.295752
ROC     7.981662
ROP     6.254630
ROR    14.118687
RST     5.783036
RSW     7.926745
SAN     7.583277
SAT     6.979337
SAV     6.684960
SBA     5.758758
SBN     3.156008
SCC    14.648810
SCK     0.287529
SDF     6.256240
SEA     9.449260
SFO     8.622028
SGF     7.448867
SHV     8.425185
SIT    10.040785
SJC     3.955744
SJU     5.789307
SLC     6.363491
SMF     6.566626
SNA     5.362499
SPN     5.706017
SRQ     7.596901
STL     4.880907
STT     3.573432
STX     4.188554
SUN    22.815789
SUX     6.719050
SWF    10.140813
SYR     6.829898
TLH     3.851421
TOL     7.042154
TPA     6.700325
TRI     3.468801
TUL     8.025631
TUS     9.059098
TVC     6.966601
TVL     1.272615
TYS     6.538309
UCA     1.568915
VPS     1.171456
WRG     8.794408
YAK     7.709576
YAP    23.293233
YUM     3.883364
Name: ArrDelay, dtype: float64

Here I loaded in the 1990 airport data and used the groupby function to group the destinations. Then I showed the mean arrival delays using .mean().

## Question 2

Find the sum of the amount spent (in the SPEND column) at each of the store regions (the STORE_R column).

In [4]:
myDF = pd.read_csv("/anvil/projects/tdm/data/8451/The_Complete_Journey_2_Master/5000_transactions.csv")
myDF.columns = ["BASKET_NUM", "HSHD_NUM", "PURCHASE", "PRODUCT_NUM", "SPEND", "UNITS", "STORE_R", "WEEK_NUM", "YEAR"]
myDF.groupby('STORE_R')['SPEND'].sum()

STORE_R
CENTRAL     8897305.14
EAST       11699446.86
SOUTH       7957920.77
WEST        9680106.54
Name: SPEND, dtype: float64

Here I loaded the 5000_transactions.csv and assigned the column headers. I then and used the groupby function to group the store regions together. Then I showed the sum money spent using .sum().

## Question 3

Find the total amount of money spent in 2016 altogether, and the total amount of money spent in 2017 altogether. (You can use the groupby to do this with just one cell.)

In [11]:
myDF.groupby('YEAR')['SPEND'].sum()

YEAR
2016    19051720.01
2017    19183059.30
Name: SPEND, dtype: float64

For this problem, I used the groupby function to group the years together. Then I showed the sum money spent using .sum().

## Question 4

Find the average height of the athletes in each country (the country is the NOC column).

In [16]:
myDF = pd.read_csv("/anvil/projects/tdm/data/olympics/athlete_events.csv")
myDF.groupby('NOC')['Height'].mean()

NOC
AFG    170.592593
AHO    177.294118
ALB    173.000000
ALG    174.702869
AND    173.703704
ANG    178.204082
ANT    175.121739
ANZ    176.730769
ARG    176.604722
ARM    171.937799
ARU    173.219512
ASA    175.666667
AUS    176.874017
AUT    177.369686
AZE    172.717391
BAH    177.440678
BAN    166.187500
BAR    176.598958
BDI    172.631579
BEL    176.143175
BEN    173.683333
BER    177.405797
BHU    166.517241
BIH    178.633929
BIZ    175.054795
BLR    174.256440
BOH    174.000000
BOL    171.295652
BOT    175.809524
BRA    177.637147
BRN    173.424528
BRU    166.111111
BUL    172.830911
BUR    176.000000
CAF    179.276596
CAM    166.719298
CAN    174.978716
CAY    179.506849
CGO    174.585366
CHA    176.558824
CHI    174.986989
CHN    172.602743
CIV    176.415094
CMR    173.634615
COD    175.358209
COK    171.324324
COL    169.915220
COM    170.866667
CPV    175.888889
CRC    174.304762
CRO    183.613174
CRT           NaN
CUB    174.908228
CYP    176.675393
CZE    178.169428
DEN    179.200997
DJI    173.419355
DMA    174.888889
DOM    172.216981
ECU    171.142857
EGY    178.104478
ERI    169.945946
ESA    169.560694
ESP    174.921725
EST    179.301863
ETH    170.230114
EUN    177.069638
FIJ    177.420290
FIN    175.757945
FRA    175.254745
FRG    177.641809
FSM    161.240000
GAB    171.500000
GAM    170.550000
GBR    175.722488
GBS    169.500000
GDR    175.553053
GEO    175.010526
GEQ    170.260870
GER    177.344479
GHA    173.881188
GRE    176.783333
GRN    175.166667
GUA    171.148936
GUI    172.887097
GUM    176.585366
GUY    174.476190
HAI    173.930556
HKG    172.214400
HON    173.546763
HUN    175.881507
INA    167.488235
IND    171.638608
IOA    177.029412
IRI    174.848974
IRL    176.614286
IRQ    173.889571
ISL    181.245413
ISR    173.245347
ISV    177.933333
ITA    175.298943
IVB    178.631579
JAM    176.168512
JOR    173.188406
JPN    168.228163
KAZ    175.465683
KEN    171.981481
KGZ    178.075000
KIR    166.909091
KOR    171.992278
KOS    173.500000
KSA    173.144385
KUW    174.500000
LAO    166.431373
LAT    179.644501
LBA    168.465517
LBR    173.611111
LCA    174.888889
LES    167.254902
LIB    173.363229
LIE    175.282609
LTU    182.099502
LUX    173.872642
MAD    168.464286
MAL    167.250000
MAR    173.593220
MAS    170.490281
MAW    165.950000
MDA    176.018018
MDV    163.761905
MEX    171.912115
MGL    169.133470
MHL    168.538462
MKD    174.890411
MLI    180.606557
MLT    169.918605
MNE    183.563830
MON    176.260870
MOZ    172.631579
MRI    174.342342
MTN    173.607143
MYA    166.106383
NAM    172.859155
NBO           NaN
NCA    169.666667
NED    179.488906
NEP    163.905882
NFL    170.000000
NGR    174.718291
NIG    172.400000
NOR    178.002397
NRU    167.181818
NZL    177.832850
OMA    169.656250
PAK    173.910082
PAN    171.882353
PAR    176.584158
PER    173.545232
PHI    170.268061
PLE    169.666667
PLW    165.458333
PNG    170.425743
POL    175.265043
POR    173.525000
PRK    161.557960
PUR    177.376197
QAT    178.325581
RHO    169.333333
ROT    169.916667
ROU    172.553622
RSA    177.785384
RUS    176.214419
RWA    167.916667
SAA    159.666667
SAM    174.826087
SCG    187.511401
SEN    180.178886
SEY    175.500000
SGP    171.076628
SKN    175.205128
SLE    177.039604
SLO    177.226744
SMR    176.528662
SOL    169.230769
SOM    176.000000
SRB    184.635204
SRI    169.626016
SSD    173.333333
STP    172.333333
SUD    173.902174
SUI    175.221613
SUR    171.368421
SVK    178.170192
SWE    177.942064
SWZ    171.527273
SYR    174.454545
TAN    169.637584
TCH    174.917967
TGA    179.305556
THA    168.354167
TJK    174.569231
TKM    173.245283
TLS    161.444444
TOG    172.698113
TPE    169.622391
TTO    176.974138
TUN    178.528409
TUR    173.814700
TUV    165.750000
UAE    172.653846
UAR    181.000000
UGA    172.058296
UKR    174.187474
UNK           NaN
URS    175.063243
URU    176.353623
USA    176.886903
UZB    176.015284
VAN    169.290323
VEN    174.144121
VIE    165.136986
VIN    177.043478
VNM    165.763158
WIF    178.000000
YAR    167.400000
YEM    167.960000
YMD    175.000000
YUG    178.646061
ZAM    172.828125
ZIM    173.364583
Name: Height, dtype: float64

I first loaded in the athlete_events dataset. I then used the groupby function to group the countries (NOC) together. Then I showed the average height using .mean().

## Question 5

Find the average height of the athletes in each sport

In [17]:
myDF.groupby('Sport')['Height'].mean()

Sport
Aeronautics                         NaN
Alpine Skiing                173.489052
Alpinism                            NaN
Archery                      173.203085
Art Competitions             174.644068
Athletics                    176.256268
Badminton                    174.178803
Baseball                     182.599291
Basketball                   190.869879
Basque Pelota                       NaN
Beach Volleyball             186.144954
Biathlon                     174.034766
Bobsleigh                    181.437500
Boxing                       172.825688
Canoeing                     178.539568
Cricket                             NaN
Croquet                             NaN
Cross Country Skiing         173.249185
Curling                      174.203125
Cycling                      176.108826
Diving                       166.634264
Equestrianism                174.375272
Fencing                      177.164177
Figure Skating               168.202160
Football                     175.402195
Freestyle Skiing             171.012959
Golf                         174.290076
Gymnastics                   162.936020
Handball                     183.384592
Hockey                       173.359676
Ice Hockey                   178.901323
Jeu De Paume                 178.500000
Judo                         174.187353
Lacrosse                     174.000000
Luge                         176.657742
Military Ski Patrol                 NaN
Modern Pentathlon            177.944316
Motorboating                 181.000000
Nordic Combined              176.504464
Polo                         175.500000
Racquets                     176.000000
Rhythmic Gymnastics          167.870253
Roque                               NaN
Rowing                       184.172222
Rugby                        176.096774
Rugby Sevens                 175.363636
Sailing                      178.262199
Shooting                     173.572174
Short Track Speed Skating    170.108199
Skeleton                     176.188571
Ski Jumping                  176.402757
Snowboarding                 173.085561
Softball                     169.395089
Speed Skating                174.083352
Swimming                     178.562454
Synchronized Swimming        168.481481
Table Tennis                 171.253773
Taekwondo                    176.750836
Tennis                       178.898139
Trampolining                 166.582781
Triathlon                    173.645833
Tug-Of-War                   182.480000
Volleyball                   186.994822
Water Polo                   184.834648
Weightlifting                167.824801
Wrestling                    172.358586
Name: Height, dtype: float64

Similarly to the previous problem, I used the groupby function to group the sport names together. Then I showed the average height using .mean().

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.